export enum AuditLogActionType {
    SENT_TO_FIRST_RECIPIENT = "SENT_TO_FIRST_RECIPIENT",
    RECIPIENT_OPENED = "RECIPIENT_OPENED",
    SENT_TO_NEXT_RECIPIENT = "SENT_TO_NEXT_RECIPIENT",
    ALL_RECIPIENTS_COMPLETED = "ALL_RECIPIENTS_COMPLETED"
}

export enum AuditLogTag {
    TEMPLATE_FLOW = "TEMPLATE_FLOW"
}